name: 🚀 自動外送網頁到免費主機

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 全自動多專案同步
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 步驟1：取得最新程式碼
      uses: actions/checkout@v4

    - name: 📂 步驟2：全自動建立多層資料夾並同步
      uses: wlixcc/SFTP-Deploy-Action@v1.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        remote_path: ./htdocs/HTML_PRACTICE/